### ISSUE TITLE
How could I use this library if I want a distributed geospatial solution?

### ISSUE THREAD

**Issue by yingfeng** [uber/h3#135]

**Comment by nrabinowitz** [comment]
This question needs more clarification in order to solicit a useful answer. I'd also suggest moving it to StackOverflow, as we'd like to keep GitHub issues for bug reports or feature requests, rather than general questions.

I'm going to close this for now; please re-open on StackOverflow with more context on what you're trying to do and what issues you're facing, and tag it with `h3`. Thanks!
