### ISSUE TITLE
Where is the definition for pointInsideLinkedGeoLoop?

### ISSUE THREAD

**Issue by danvanderboom** [uber/h3#164]
I see pointInsideLinkedGeoLoop in the linkedGeo.h header file:
`bool pointInsideLinkedGeoLoop(const LinkedGeoLoop* loop, const BBox* bbox, const GeoCoord* coord);`

But I don't see the function's implementation anywhere. Searching the solution, I can see it used a couple times, but not defined. Is it an external dependency? 

I'm not very strong in C. What am I missing?

**Comment by danvanderboom** [comment]
![image](https://user-images.githubusercontent.com/2482850/49903209-492c1d00-fe1b-11e8-8ec5-587ef78c0d3d.png)

**Comment by RichardVasquez** [comment]
> I see pointInsideLinkedGeoLoop in the linkedGeo.h header file:
> `bool pointInsideLinkedGeoLoop(const LinkedGeoLoop* loop, const BBox* bbox, const GeoCoord* coord);`
> 
> But I don't see the function's implementation anywhere. Searching the solution, I can see it used a couple times, but not defined. Is it an external dependency?
> 
> I'm not very strong in C. What am I missing?

It's in there, but as #defines within polygon.h (the ITERATE named macros) that are also used in other header files like linkedGeo.h, which eventually lead you to polygonAlgos.h where these macros are replaced with appropriate values that get defined, in one example, at the bottom of linkedGeo.c

When I was converting this to C#, it made for an interesting chase, but it had also been a while since I'd written any serious C.  This might be a good starting point to understand what #define can do, and what the H3 folks have used it for:  https://gcc.gnu.org/onlinedocs/cpp/Macros.html

**Comment by nrabinowitz** [comment]
@RichardVasquez is correct, the definition is inside `polygonAlgos.h`: https://github.com/uber/h3/blob/master/src/h3lib/include/polygonAlgos.h#L66

The reason for this is that we needed it to operate over two different iterable data structures, `Geofence` and `LinkedGeoLoop`, and C doesn't have great support for this type of polymorphism. Ideally we'd only have one polygon representation, but... reasons, which I can go into if you're interested.

**Comment by danvanderboom** [comment]
@RichardVasquez Thanks for the macros link, and for the great work on your H3 to C# conversion. I've been doing my own conversion to C# this week, had looked around before I did, and am surprised I missed your project on GitHub. It'll save me lots of time. 🥇

**Comment by danvanderboom** [comment]
@nrabinowitz I'm curious to know. Can one be converted into the other, and back? Convert and iterate wouldn't work here?

**Comment by nrabinowitz** [comment]
@danvanderboom The reason we have the two different structures is primarily due to memory management. For `polyfill`, the caller is constructing the geo polygon, so they can allocate an appropriate amount of memory, and the current `Geofence` struct is an efficient format in which to pass the polygon coords. We originally wrote `pointInsideGeofence` in service of the `polyfill` algo. `LinkedGeoLoop` was needed for `h3SetToLinkedGeo`, because the caller doesn't know how much memory to allocate for the output polygon, and the max theoretical size might be orders of magnitude larger than the real required size, so we have the caller allocate the first node, link the rest, and then ask them to destroy the structure after they read it to free the memory allocated by the algo.

So that left us with two polygon structures, and we couldn't easily switch the API to use only one. There's a current work item for the next major version to possibly consolidate around one structure, but for now we have two. And while it's possible to convert between them, this is `O(vertices)` at best and uses twice the memory, and the polygons in question may have very large numbers of vertices. When we moved multipolygon normalization into the core library (#131), we needed the point-in-poly and bounding box algos to work on the `LinkedGeoLoop` structure as well. The options considered were to a) duplicate the code to work on the new structure, b) convert into a `Geofence` and then convert back, or c) use macros to allow some form of polymorphism. (a) feels ugly and hard to maintain, (b) had performance concerns, and (c) results in less legible code, but given the tradeoffs (c) won out.

Hopefully we can clean this up in v4 by consolidating on one geo type, but we don't have a clear v4 timeline at present.
