### ISSUE TITLE
_hex2dToCoordIJK() redundant code or something else

### ISSUE THREAD

**Issue by zhaone** [uber/h3#199]
I found the following code  when learning your algorithm. 
https://github.com/uber/h3/blob/d610a226df755b0a91d1012cb12496525b1a1926/src/h3lib/lib/coordijk.c#L67-L83
In this way, under any condition, `r1==r2==0`. Only this code
https://github.com/uber/h3/blob/d610a226df755b0a91d1012cb12496525b1a1926/src/h3lib/lib/coordijk.c#L78-L79
will execute and the following bunch of if statements make no sense, does it? There should be some judgment in previous version according to your comment(line 67 71). Seems that you had modified some code here, I want to know if this execution process can execute the algorithm correctly?

**Comment by isaacbrodsky** [comment]
Hi, I believe this code is reachable in at least this case from the test files:
```
v.x = 17.499999999962203
v.y = -6.0621778265014115
```

In this case,
```
a1 = 17.499999999962203
a2 = 6.0621778265014115

x2 = 7.0000000000119407
x1 = 20.999999999968175

m1 = 20
m2 = 7

r1 = 0.99999999996817479
r2 = 0.000000000011940670674448484
```

I think the thing to note here is that `m1` and `m2` are integers, so lines 68 and 69 are truncating (rounding), which is why lines 72 and 73 are not necessarily 0. It might be clearer to explicitly cast to `int` in the code so that's clearer.

**Comment by zhaone** [comment]
Thanks! I failed to notice data type.
