### ISSUE TITLE
API with integers as parameter

### ISSUE THREAD

**Issue by numansheikh-kt** [uber/h3#204]
Wouldn't it be more appropriate to use 64bit int as the standard parameter as well as return type when identifying hexagons (especially with languages like Python) instead of hexadecimal strings? 
This would have made much more sense for faster comparison and database indexing. I know we can convert it but that adds extra computations every time.

**Comment by nrabinowitz** [comment]
This is more of a question for the bindings than the core library, since the C lib does use 64-bit ints as the data type for H3 indexes. 
- The Java and Go bindings do offer 64-bit representations as a first-class citizen.
- I am less familiar with the considerations for Python (@TengHu or @karentycoon might be better resources here) but my understanding is that (at least for some versions) Python doesn't have native support for 64-bit integers. If Python is the main concern here, I'd recommend filing a ticket against [h3-py](https://github.com/uber/h3-py).
- Javascript has no support for 64-bit integers, so strings are the only option.

 The general path we've taken in designing applications using H3 is to use the string representation for data transfer between services/applications and to use whatever is most appropriate and performant inside of a given service, depending on the language used. So a Go service might use 64-bit ints internally, but use strings as the canonical data transfer format in its API.
