### ISSUE TITLE
A question about h3ToGeoBoundary

### ISSUE THREAD

**Issue by Slawlight** [uber/h3#205]
In the function h3ToGeoBoundary, why it used the intersection to replace the real vertex of the hexagon in some cases?

**Comment by sahrk** [comment]
H3 is defined on an icosahedron, where each face of the icosahedron is projected to the sphere using an inverse gnomonic projection centered on that face. Each face-centered gnomonic projection maps the cell boundaries that lie on that face to great circle arcs on the sphere. But when a cell boundary crosses an icosahedron edge, it moves between two projection spaces. So we introduce a vertex wherever a boundary intersects an edge so that each part of the boundary can be projected independently using the appropriate face’s projection. These new vertexes do not replace the original vertexes; they are in addition to them.
