### ISSUE TITLE
h3ToFaceIjk

### ISSUE THREAD

**Issue by helloniuniu** [uber/h3#232]
It is possible that ijk lies on an adjacent face, so we may need to adjust adjust for overage.

But I notice that a pentagon base cell with a leading 4 digit requires special handling, i want to know why? 

And when adjusting for the pentagonal missing sequence, why in the ik quadrant instead of the ij/jk quadrant?

`    // adjust for overage if needed
    // a pentagon base cell with a leading 4 digit requires special handling
    int pentLeading4 =
        (_isBaseCellPentagon(c.baseCell) && _leadingNonZeroDigit(&c) == 4);
    if (_adjustOverageClassII(fijk, res, pentLeading4, 0))`

`int _adjustOverageClassII(FaceIJK* fijk, int res, int pentLeading4,
                          int substrate) {
    int overage = 0;

    CoordIJK* ijk = &fijk->coord;

    // get the maximum dimension value; scale if a substrate grid
    int maxDim = maxDimByCIIres[res];
    if (substrate) maxDim *= 3;

    // check for overage
    if (substrate && ijk->i + ijk->j + ijk->k == maxDim)  // on edge
        overage = 1;
    else if (ijk->i + ijk->j + ijk->k > maxDim)  // overage
    {
        overage = 2;

        const FaceOrientIJK* fijkOrient;
        if (ijk->k > 0) {
            if (ijk->j > 0)  // jk "quadrant"
                fijkOrient = &faceNeighbors[fijk->face][JK];
            else  // ik "quadrant"
            {
                fijkOrient = &faceNeighbors[fijk->face][KI];

                // adjust for the pentagonal missing sequence
                if (pentLeading4) {
                    // translate origin to center of pentagon
                    CoordIJK origin;
                    _setIJK(&origin, maxDim, 0, 0);
                    CoordIJK tmp;
                    _ijkSub(ijk, &origin, &tmp);
                    // rotate to adjust for the missing sequence
                    _ijkRotate60cw(&tmp);
                    // translate the origin back to the center of the triangle
                    _ijkAdd(&tmp, &origin, ijk);
                }
            }
        } else  // ij "quadrant"
            fijkOrient = &faceNeighbors[fijk->face][IJ];

        fijk->face = fijkOrient->face;

        // rotate and translate for adjacent face
        for (int i = 0; i < fijkOrient->ccwRot60; i++) _ijkRotate60ccw(ijk);

        CoordIJK transVec = fijkOrient->translate;
        int unitScale = unitScaleByCIIres[res];
        if (substrate) unitScale *= 3;
        _ijkScale(&transVec, unitScale);
        _ijkAdd(ijk, &transVec, ijk);
        _ijkNormalize(ijk);

        // overage points on pentagon boundaries can end up on edges
        if (substrate && ijk->i + ijk->j + ijk->k == maxDim)  // on edge
            overage = 1;
    }

    return overage;
}`

**Comment by sahrk** [comment]
In a CPI system like H3 ([see my paper](https://utpjournals.press/doi/abs/10.3138/cart.54.1.2018-0022)) the hexagonal indexing hierarchy is applied to pentagons by deleting one of the 7 hexagonal indexing subsequences (numbered 0-6). For H3 we chose to delete subsequences beginning with digit 1, which is the k-axis direction ([see documentation](https://uber.github.io/h3/#/documentation/core-library/h3-index-representations)). Each pentagonal base cell is associated with a home icosahedral face such that the deleted digit 1 subsequence lies entirely off that home face. This way we never have to worry about the deleted subsequence when working on the home icosahedral face. 

The algorithm begins by assuming that each cell is a planar hexagon. Geometrically this is as if each icosahedral vertex base cell straddles six icosahedral faces, but in reality of course on the sphere it only straddles five. We delete the face on the plane that contains part of the digit 4 and digit 5 subsequences (the ik "quadrant") by rotating that face clockwise onto the face that originally contains part of the digit 5 and digit 1 subsequences. This is done in the ik quadrant because it lies entirely off of the icosahedral face, so again we never need to perform this compensation as long as we are on the home icosahedral face.

I had a hand-drawn illustration of this that I'll try to recreate for the documentation at some point (alas the original is somewhere with Uber).

**Comment by helloniuniu** [comment]
> 在像H3这样的CPI系统中（[参见我的论文](https://utpjournals.press/doi/abs/10.3138/cart.54.1.2018-0022)），通过删除7个六边形索引子序列中的一个（编号为0-6），将六边形索引层次应用于五边形。对于H3，我们选择删除以数字1开头的子序列，即k轴方向（[参见文档](https://uber.github.io/h3/#/documentation/core-library/h3-index-representations)）。每个五边形基本单元与家庭二十面体面相关联，使得删除的数字1子序列完全脱离该主面。这样我们就不必担心在家庭二十面体上工作时删除的子序列。
> 
> 该算法首先假设每个单元是平面六边形。几何上，这就像每个二十面体顶点基本细胞跨越六个二十面体面，但实际上当然在球体上它只跨越五个。我们通过将该面顺时针旋转到最初包含数字5和数字1子序列的一部分的面上，删除包含数字4和数字5子序列（ik“象限”）的一部分的平面上的面。这是在ik象限中完成的，因为它完全位于二十面体上，所以只要我们在家庭的二十面体上，我们再也不需要进行这种补偿。
> 
> 我有一个手绘的插图，我会尝试在某些时候重新创建文档（唉原来是优步的某个地方）。

**Comment by helloniuniu** [comment]
Aha,I  I drew two illustration, is that right?
![II-24-F1](https://user-images.githubusercontent.com/37333122/57898680-b5a8bd80-788c-11e9-9d12-59448d41dc60.jpg)
![F1](https://user-images.githubusercontent.com/37333122/57898724-d6711300-788c-11e9-9557-bd08cb58a878.jpg)

Thank you very much for your answer. I think I understand.

**Comment by sahrk** [comment]
I didn't verify the H3 indexes you used, but yes, the illustration is correct.
