### ISSUE TITLE
iOS does not support stack array allocation

### ISSUE THREAD

**Issue by long1eu** [uber/h3#233]
On iOS I get this error:

```
This platform does not support stack array allocation, please submit an issue on https://github.com/uber/h3 to report this error.
```

**Comment by isaacbrodsky** [comment]
Thanks for reporting this. Could you also post the C compiler version being used? (E.g. output of `cc --version`)

Since stack array allocation is currently only used in the test suite, I think it makes sense for us to convert those back to `calloc` calls.

As a simple change to get the library compiling, you may be able to comment out the contents of the file `src/h3lib/include/stackAlloc.h`. Without changing the test suite, you will not be able to build the test suite or the filter applications.

**Comment by long1eu** [comment]
Sure
```
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
