### ISSUE TITLE
Querying integer range of ID to check if child

### ISSUE THREAD

**Issue by thegeebe** [uber/h3#248]
In S2, one useful property of IDs is that for a particular cell _C_, one can compute a min and max integer cell ID, such that all cell IDs contained in this range are children of _C_, regardless child level/resolution. This is useful when configuring an index in a database to perform containment queries.

Do H3 indexes have a similar property, whereby one may check if a cell is a child of another with a simple range query? Is there another indexing mode where this is possible?

**Comment by isaacbrodsky** [comment]
Yes, the H3 index is hierarchical and should support this. Because the H3 index records its resolution, unlike S2, I think it would require constructing a range for a specific resolution. The lower bound would be (higher resolution and) all indexing digits after the ancestor are 0 and the upper inclusive bound would be (higher resolution and) all indexing digits after the ancestor are 6.

You should be able to see this in action using the `h3ToChildren` function in the library (https://uber.github.io/h3/#/documentation/api-reference/hierarchy) where the lowest and highest index are constructed in this way.

**Comment by thegeebe** [comment]
Thanks for the reply, that makes sense to me. I will close issue since it's not really and issue with the code. Interested if you agree with the following:

It seems like this would be possible with a single range if the resolution were not present in the index. Then all children of _C_ would have IDs less than _C_ and greater than the cell at _C_'s level that is "one digit less than" _C_. Since resolution can be inferred by the number of trailing 1 triplets, is it just used for efficiency in certain ops?

**Comment by dfellis** [comment]
@thegeebe you're right about that, but there are some useful properties the way it is right now.

1. All hexagons IDs in hexadecimal form begin with the digit '8' and the next digit is the resolution from 0-F, eg `geoToH3(-112, 45, 9) -> 89e3a1d01b3ffff`, and all unidirectional edge indexes begin with '1' in hexadecimal, followed by the direction digit 1-6, and then followed by the resolution 0-F, eg `getH3UnidirectionalEdgesFromHexagon('89e3a1d01b3ffff')[0] -> 119e3a1d01b3ffff`. So if you can assume that your hexagon IDs are valid, then you can very efficiently categorize them by type and resolution.
2. You have a minor improvement in proving a block of binary data is a collection of hexagons instead of some other form of data by requiring the resolution to match the digits shown, since the odds of arbitrary binary data matching that (and other constraints) is ridiculously low.

Contradicting the above, I have been thinking about utilizing the resolution and digits separately to completely replace GPS data storage if you can deal with some discretization of secondary data points.

The regular H3 index at resolution 15 is more precise than commercial GPS devices, so that one 64-bit integer can replace two 64-bit floats for lat, lng. Then if you use the resolution to indicate the precision, you can get 16 precision buckets also baked into that integer, and if you use the unidirectional edge logic you can get 6 coarse heading buckets in there as well.

If you only need rough estimates on heading and precision to inform things like road network mapmatching, then you now have a single representation that takes up between 1/2 to 1/4th the space of the traditional representation, and simple bit flipping of the leading `1[1-6][0-F]` to just be `08F` lets you feed that same data into any H3-enabled logic that only cares about position.

There's nothing in the codebase to do that (yet?) and it probably would make sense to define a [new  H3 Index Mode](https://uber.github.io/h3/#/documentation/core-library/h3-index-representations) (which could allow things like all 8 North-East-West-South-etc directions represented instead of neighbor-based directions) if/when that sort of thing is done (keeping the categorization and validation advantages for the other modes mentioned above), but the general structure of the index makes that format possible, and I could see some use-cases with it being both highly compressed and fast to operate on.

**Comment by lokkju** [comment]
I'm aware this is a dead issue, but as progress is made on some of the polyfill enhancements in #275 , it may be worth revisiting this feature. A key advantage of S2, as pointed out above, is that when used with an ordered key-value store you can index points at the highest resolution available, but then use range queries to return all children cells of a parent cell. This has major advantages when using S2's covering methods on a polygon, as it's efficient to cover the polygon with multiple S2 cells of differing levels, eventually resulting in less queries to the datastore, each query simply being a range query.
