### ISSUE TITLE
Layers on the Roadmap

### ISSUE THREAD

**Issue by Zambonilli** [uber/h3#257]
We're looking at creating layers for various datasets like topography, weather, air quality, tree cover, etc per h3 index and optionally time. These layers would be pulled into machine learning models for training and inference. 

Are there any plans for how to build, manage and distribute layers with h3 on the roadmap? I could see a future where there are open datasets shared online that could be pulled down indexed by h3Index and h3Index + time.

**Comment by dfellis** [comment]
That's probably a layer above the H3 project? The H3 index defines a region on the planet, and then you can use that index in your own data structure to assign properties to and create records you can work with.

For instance, in SQL what you've described above could form a simple table:

```
+-----------------+-------------------+---------------+                                                
| H3 Index        | Air Quality Score | Tree Coverage |                                                
+-----------------+-------------------+---------------+                                                
| 880a000001fffff |  92               | 0.63          |                                                
+-----------------+-------------------+---------------+                                                
| 880a000005fffff |  22               | 0.24          |                                                
+-----------------+-------------------+---------------+
```

You can then index on the H3 Index column to do quick lookups by H3 index, or index on the Air Quality Score and look for all H3 Indexes with a quality score below 50, etc.

Distribution can then be as simple as a .csv or .sql file, or it could be hosted in a cloud database for online access.

But adding this extra functionality doesn't make sense in the H3 project. What if the user wants to use Redis instead of MySQL, or just use the index as the key to a HashMap in their Java application? H3 is a component that can then be used in other projects with other goals where H3 is just one piece.

There is an interesting project to [give PostgreSQL access to the H3 API](https://github.com/bytesandbrains/h3-pg) for more complicated uses of H3 beyond index lookup and retrieval that might be more of what you're after, but these things should be an optional extra layer on top of this intentionally small core library.

**Comment by nrabinowitz** [comment]
I think this is a great idea, and would love to see public datasets using H3. We have not thought about this as a roadmap item, and I don't think we'd ever consider this to be part of the library, though I could imagine contributing to a separate initiative for open datasets. Internally, Uber has various systems to manage H3 layers - the design considerations for the system and data format depend largely on how important the time dimension is, and whether you're dealing with H3 indexes as the unit or H3 clusters (i.e. sets of H3 indexes defining a geographical area) as the unit.

The [Datasette project](https://github.com/simonw/datasette) might be interesting as a publishing platform for this.

**Comment by Zambonilli** [comment]
Totally on the same page that the h3 lib shouldn't support layers. I'm mainly making sure that we won't reinvent the wheel if there's already someone building, managing and deploying layers based on h3 Index or h3 clusters. The ideal would be that we create some sort of open source/data way here to share the work so others do not have to reinvent the wheel either for layers.

**Comment by nrabinowitz** [comment]
Closing, as we're unlikely to address.
