### ISSUE TITLE
Suggestion to improve h3 performance _to_ O(1), /from/ {O((log N)²); O(N(log N)²); O(log N)}

### ISSUE THREAD

**Issue by no-identd** [uber/h3#258]
You heard me, and no, I didn't typo in the title, either, I really **do** mean O(1). *How?*

Well, you'll have to read this PhD thesis to find out:
http://ufdcimages.uflib.ufl.edu/UF/E0/04/23/19/00001/rummelt_n.pdf

Here, a teaser:
![IMG_20190719_111849_806](https://user-images.githubusercontent.com/1437795/61524689-4039a480-aa17-11e9-88db-0539c3ac490f.jpg)

![IMG_20190719_111148_836](https://user-images.githubusercontent.com/1437795/61524700-462f8580-aa17-11e9-90a7-6c3a0c271e32.jpg)

The math of the 'HIP' ("Hexagonal Image Processing") coordinate system seems almost identical to what you do, so, this seems very much applicable. 

I have neither the time nor the skills to implement an improvement based on this, but… I figure the promise of this performance improvement should pose more than enough motivation for all y'all to make this a priority.

**Comment by nrabinowitz** [comment]
Most algorithms in H3 are *already* O(1) (or O(n) for operations over arrays of indexes). Is there a specific aspect of performance that you expect we could improve?

**Comment by isaacbrodsky** [comment]
Hi, thanks for the link. Unfortunately it's not clear to us how this approach could be applied to H3 given the existing grid indexing system definition. Given that I'm going to close this issue. We'd welcome more discussion of how to improve the performance of the library, and we'd certainly welcome pull requests that reduce time complexity or otherwise improve performance.

@nrabinowitz It might be useful to add complexity analysis to the H3 documentation site.
