### ISSUE TITLE
H3 terminology for types

### ISSUE THREAD

**Issue by ajfriend** [uber/h3#259]
Following up on [this comment](https://github.com/uber/h3-py/pull/51#issuecomment-513095852), we can try to use this issue to hash out precise terminology for data types in H3. (We can leave function names like `kRing` and `hexRing` to other issues.)

As terms are currently used inconsistently within the library, what we determine here should be considered "aspirational", and would hopefully get formally implemented in H3 4.x.

I'll start with my ideas for a few:

- `H3Index`, H3 index, index
    - an unsigned 64-bit integer representing **any** H3 object (hexagon, pengaton, unidirectional edge, ...)
    - often represented as a 16-character hexadecimal string, like `'8928308280fffff'`
- cell
    - an H3 index of `mode` 1
    - a cell may be a hexagon or a pentagon (but is usually a hexagon)
- hexagon
    - a hexagonal cell
- pentagon
    - a pentagonal cell

**Comment by nrabinowitz** [comment]
That's a good point, we've had a hard time being consistent here. I think we're pretty solid on `H3 index` for the 64-bit representation, but we frequently use it in the more limited sense of `cell` as well (e.g. lots of functions take an `H3 index` that must represent a cell).

One note here is that we (should) use `hexagon` topologically, based on neighbor count, rather than geometrically, based on vertex count. This can be [confusing for users](https://github.com/uber/h3-js/issues/53), though.

**Comment by ajfriend** [comment]
> One note here is that we (should) use `hexagon` topologically, based on neighbor count, rather than geometrically, based on vertex count. This can be [confusing for users](https://github.com/uber/h3-js/issues/53), though.

Interesting! Didn't know that. Also, I've seen it elsewhere but was never quite sure: What's a Class III cell?

**Comment by nrabinowitz** [comment]
> What's a Class III cell?

It's [explained in the docs here](https://uber.github.io/h3/#/documentation/core-library/coordinate-systems). The short answer is: Even resolutions are Class II, odd resolutions are Class III, and Class III cells are subject to distortion at the icosahedron edges (because unlike Class II they aren't aligned with the icosahedron face).

**Comment by ajfriend** [comment]
Tossing this into the 4.0 naming discussion: https://github.com/uber/h3-py/pull/79#discussion_r347110847

Should `h3line` be renamed to something like `h3path`?

**Comment by ajfriend** [comment]
Closed by #308
