### ISSUE TITLE
Hexbin some data

### ISSUE THREAD

**Issue by nlassaux** [uber/h3#27]
Knowing the complexity of the library, what do you think would be the efficient way to aggregate data from polygons into hexagonal shapes, taking into account the degree of overlapping?

For example, translating:

Zip code      | Count
------------ | -------------
10001 | 10
10002 | 3
10003 | 14

into: 

Hash      | Count
------------ | -------------
8a2a1072b59ffff | 3
8a2a1072b59ffee | 5
8a2a1072b59ffdd | 3
8a2a1072b59ffcc | 2
8a2a1072b59ffbb | 2

`h3ToGeoBoundary` could be used, and then classic methods to compute the overlap between each shape. But the complexity looks pretty high for that.

**Comment by dfellis** [comment]
If I've got your question right, I think you want to use the [`polyfill` function](https://github.com/uber/h3/blob/master/src/h3lib/lib/algos.c#L725) (along with the [`maxPolyfillSize` function](https://github.com/uber/h3/blob/master/src/h3lib/lib/algos.c#L587) to allocate the required memory). It takes a GeoJSON-like struct defining the area to fill, and it guarantees perfectly contiguous geometries have no overlapping hexagons (though the hexagons themselves may overlap the geometries, each overlapping hexagon will be in one or the other geofence, never both).

The bindings (that @isaacbrodsky is working on getting open sourced hopefully this month) handled the GeoJSON to GeoJSON-like struct conversion for you.

After that, you would just take the value for the zip code geofence and divide it equally amongst the hexagons in the polyfilled zip code hexagon array.

**Comment by joegilley** [comment]
+1 to @dfellis 's answer.  only caveat i can see is for his solution alone, there isn't any weighted distribution possible for hexagons that have geometry overlapping a polygon boundary because they'll be assigned one side or another, like he said.

so for the portion of your question "taking into account degree of overlapping", you might have to implement post-processing with a degree of sophistication appropriate for your use case.

depending on your use case, you could avoid that by using sufficiently high resolution hexagon cells and stick with @dfellis's solution :)

**Comment by nrabinowitz** [comment]
Closing this as resolved, please reopen if the answers here have any issues.
