### ISSUE TITLE
Why does the h3ToChildren function return invalid indexes instead of filtering them out?

### ISSUE THREAD

**Issue by dimchansky** [uber/h3#289]
I would like to understand why the [h3ToChildren](https://github.com/uber/h3/blob/30b9353a738074d82ee9bfb0d8e259f6bdb9395d/src/h3lib/lib/h3Index.c#L208) function returns invalid indexes, instead of filtering them out. At first glance, it seems that using an invalid index as a terminator (like \0 NUL terminator in C-strings) would be more reasonable. On the other hand, I understand that filling an array with invalid indexes leaves you the possibility to quickly jump between the children hexagons in the array, because you just need to skip predictable and deterministic number of indexes to get all the children at specific direction. It seems that cases when the array is filled with invalid indexes are quite rare and it is easier to leave them in the array in order to be able to quickly jump between children. Is this true or are there any other reasons (like possibility to parallelise etc.)?

**Comment by dfellis** [comment]
So there are a few reasons for why this function and its return are structured the way they are.

1. The only time there will be an invalid indexes mixed in with valid indexes is if a pentagon is encountered (because internally the pentagons are hexagons with one of the six faces omitted). The only time a pentagon is encountered amongst the children of an index is if the parent index is a pentagon itself, so this is a very rare case and optimizing for it did not seem wise (scanning the output and resorting when the vast majority of the time it would not matter and just slow the function down).
2. This array is not analogous to a C string; the closest analogy would be a Pascal string. The caller provides a block of memory and that block of memory must be equal to or greater than `maxH3ToChildrenSize`, so there is no need for a terminator value. Knowing the total size up front does make it possible for the user of the function to perform vectorized operations on the output. It's possible that vectorized computation on the invalid index value (which is also 0, btw) could cause problems, but since that scenario can only be reached if the parent is itself a pentagon, using the `h3IsPentagon` function to test the inputs (either in-line or before the batch of hexagons are given to the user's algorithm) and switching to a fallback non-vectorized loop over the inputs seems reasonable, or simply doing the vectorized computation and a scan afterwards for the known bad output and re-zeroing it.
3. Leaving the indexes in order does provide other advantages, as well -- the indexes should be in sorted order (with a block of zeroes for the invalid direction if the parent is a pentagon) and that sorted order also matches a tree structure with 7 children per node and the array representing the final leaves of the tree. Knowing the first child in the array and the length of the array it should be possible to determine if a given index is contained in that set in O(1) time (however, that's essentially what `h3ToParent` gives you so I wouldn't do it that way, but it still feels to me that maintaining that property should enable some esoteric usage to operate much faster than the full array scan that would be needed if the output was sorted and the ordering impacted).
4. Users of the library could easily wrap the output in `qsort` or equivalent if they do not need the above properties and want to write loops that have early termination like C-string-style loops (or they could just use the detection of 0 as an indication to immediately increment the array counter by 1/7th the total array length and get the same behavior with less compute time).

I hope that explains the reasoning behind it!

**Comment by nrabinowitz** [comment]
@dfellis - why don't we return the *exact* number of children in `maxH3ToChildrenSize`? Surely we know this, because we can't encounter a pentagon unless the input index is a pentagon, right? Then we could simply skip the invalid index and continue filling the array?

**Comment by dfellis** [comment]
So the tree-like property would go away (where a given H3 index has an easily predictable location in the output array based on the direction digits below the parent direction digits). But it might speed up the algorithm (it would only check for the pentagon condition once instead of on all children).

It would complicate the `maxH3ToChildrenSize`, though, and re-use of the memory block would be more difficult. If you happened to test a pentagon on your first parent index then reusing that undersized block would then fail for the hexagons. If you started with a hexagon and then went to a pentagon, you'd need to re-zero the memory block between calls or you could accidentally think the pentagon has some children from the prior call.

So I see trade-offs here, but there is a positive I hadn't considered before. I think it's worth more discussion, at least.

**Comment by dfellis** [comment]
Oh, to do that, though, we'd have to go from this recursive implementation to a looping implementation, because we'd want to keep state tracking about the array offset and how it would be affected by the chain of pentagons in the output, so basically a full rewrite of the function would be necessary.

**Comment by nrabinowitz** [comment]
> If you happened to test a pentagon on your first parent index then reusing that undersized block would then fail for the hexagons. If you started with a hexagon and then went to a pentagon, you'd need to re-zero the memory block between calls or you could accidentally think the pentagon has some children from the prior call.

This is the part I'm confused about - unless I'm mistaken, you can *never* get a pentagon from a hexagon parent, and an input pentagon will always have one child pentagon at every resolution. So if the input index is a hexagon, you know you have `7 ** (childRes - parentRes)` indexes in the output, and if the input is a pentagon, you can calculate 
```
int count = 0;
while (parentRes++ < childRes)
  // 5 child hexagons and their 7 children
  count += 5 * 7 ** (childRes - parentRes) + 
    // One pentagon and its 6 children
    6 ** (childRes - parentRes);
```
(I think that's right, haven't double-checked).

You may be right about needed to rewrite the indexing in the function, though, I haven't checked.

**Comment by dfellis** [comment]
> > If you happened to test a pentagon on your first parent index then reusing that undersized block would then fail for the hexagons. If you started with a hexagon and then went to a pentagon, you'd need to re-zero the memory block between calls or you could accidentally think the pentagon has some children from the prior call.
> 
> This is the part I'm confused about - unless I'm mistaken, you can _never_ get a pentagon from a hexagon parent, and an input pentagon will always have one child pentagon at every resolution. So if the input index is a hexagon, you know you have `7 ** (childRes - parentRes)` indexes in the output, and if the input is a pentagon, you can calculate

You are absolutely *not* mistaken. That's correct. What I'm trying to point out, though, is that if you're working with an array of H3 Indexes you want to get the children from, an immediate optimization you can make that works perfectly fine right now is to do a single memory allocation for a given resolution, so if you know all of your hexagons are in the same resolution, you can allocate the space once and then reuse it on multiple calls to actually get the children (and do whatever it was you wanted with them).

While its true that changing this behavior would not break the API in any explicit way, the implicit contract that existing code might already be expecting would fail and then you can get one of the two errors I mentioned above (either OOB access if the first index was a pentagon and the allocated memory is reused for a hexagon, or accidentally including children for pentagons from the previous hexagon if the order was the other way around) and the most insidious part is that the vast majority of the time this would never cause a problem because there are only 12 pentagons for a given resolution and they're all in the water, so I could see this change cause a latent error to exist in others' code for years before its uncovered.

Does that clarify things?

I'm currently thinking it's worthwhile to explore the loop-plus-counter algorithm with all of the indexes at the beginning, because as I think about it maintaining the "tree order" doesn't seem to have any use-cases that you couldn't already get from usage of `h3ToParent` instead, but I think the `maxH3ToChildrenSize` should be left at the hexagon size no matter the index input and the pentagon path of this new `h3ToChildren` method should explicitly zeroes the end of the array to make sure the potential bugs noted above are avoided.

**Comment by dfellis** [comment]
The bindings don't run into this because they allocate a chunk of memory on each call, execute the function, then copy the data out into the native data types of the language and deallocate the memory, but I'm sure at some point in the future, especially for the Java or Go bindings, someone is going to want to pass in a preallocated buffer to use on all of their calls to rip the `malloc` and `free` calls out of their loop and improve the performance of the bindings for their particular use-case.

**Comment by dimchansky** [comment]
@dfellis Thank you for the detailed answer! I had this question because I started porting the H3 core code to pure Go and I noticed that this place could be optimised. I have not decided yet exactly how the function signature will look, but so far [I have left the option to transfer an empty slice](https://github.com/dimchansky/h3-go/blob/dd12301ae20e8dc7674d27d02b3f80254def07a8/h3index.go#L222) with sufficient capacity, and the function will return the filled slice. And when I ported this code, I realized that it would be possible to simply filter invalid indexes out. In any case, I think first porting/transpiling the code as it is, and then adjust it to idiomatic Go styling and make further optimisations. Therefore, your answer will be very useful in the future. Thanks! I have no more questions about this function.
