### ISSUE TITLE
Areas are not all regular hexagons?

### ISSUE THREAD

**Issue by Jinnrry** [uber/h3#292]
![image](https://user-images.githubusercontent.com/19919556/69926749-9f90e080-14f0-11ea-856e-ffe578144a75.png)

If I want to get a regular hexagon, is there any good way?

**Comment by isaacbrodsky** [comment]
No, H3 does not support this. This is a result of H3's choice to use the gnomonic projection as well as other choices about how the cell subdivision process works.

If you did have regular hexagons I wouldn't expect them to appear as regular on a Mercator map because of distortion in that projection. Can you share what you would hope to gain with regular hexagons?

**Comment by sahrk** [comment]
The cells are regular hexagons in `hex2d` space, which is the planar icosahedral gnomonic space scaled so that hex centers are one unit apart (see [documentation](https://uber.github.io/h3/#/documentation/core-library/coordinate-systems)). If you want regular hexagons that are all on a single icosahedron face I think you could get the cell boundaries in geographic coordinates and then use `_geoToHex2d` to transform the vertices to `hex2d` coordinates. If you want cells on multiple faces, you'd have to handle arranging the faces on the plane.

**Comment by Jinnrry** [comment]
Thanks! I implemented an algorithm myself.  This is my solution:
1.  Convert latitude and longitude to x and y coordinates . (https://wiki.openstreetmap.org/wiki/Mercator)
2. Calculate hexagon coordinates using mathematical equations
3. Conver x and y to latitude and longitude
