### ISSUE TITLE
Turning resolution up to 11...I mean 16

### ISSUE THREAD

**Issue by datamacgyver** [uber/h3#318]
How hard would it be to add a level of resolution to h3? I'm not a c native speaker but most of the code I've poked around in simply has a raise when a resolution higher than allowed is given. 

I know the index would have to exceed 64 bits in this instance but that could be a price worth paying for those of us with high precision observations. 

I suppose what I'm asking is: Is the problem small enough that someone with pretty basic C could have a play or is it going to involve some heavy lifting from either a "proper" programmer or a mathematician?  I'm trying to assess if it's worth me having a go.

**Comment by dfellis** [comment]
So the subdivision algorithm could go all the way to the planck length and not really have any issues, but to represent anything beyond resolutions 0-15 you need to store things in a C struct instead of an integer. Very early on in the life of this project there was such a representation, but there are many issues with interoperability with structs that it was eliminated.

Basically, each CPU architecture your code is compiled to can have a slightly different layout of your C struct (some can handle simple byte alignment, while others prefer addresses to be 32 or 64 bit spaced apart, so an int8 would have 24 bits of padding afterwards on those platforms), meaning that while you can write C code that uses that struct and you can write bindings to another language that uses that struct, you *cannot* use that struct as an interchange format. Different machines will be unable to properly process the raw bytes of the struct from other machines.

That eliminates a whole class of uses, as an H3 struct can only be used as internal implementation details of the program using it.

We have discussed in the past creating a new H3 index mode that implies a second 64-bit integer that could add ~21 more resolutions (0-36) or even a nearly unbounded index that declares the next `n` 64-bit integers for storing parent-child traversal information, but had not seen a use-case as commercial GPS is not as accurate as res 15. The issue with these is that the 64-bit integer is no longer valid, the array of such integers is the valid index, so it makes parsing, operations on them, and especially *indexing* on them (eg in a database) more difficult.

There is one final option: when you look at the [raw bitfields of the H3Index](https://h3geo.org/#/documentation/core-library/h3-index-representations) you may notice that there is both a resolution field and the values for all 16 resolutions possible, and if you look at the specification of the resolution parent->child traversal rules, 0-6 are valid while 7 is invalid (hence why most H3 indexes end in a bunch of `f`s, `7 decimal == 111 binary` and `f` in hexadecimal is also all 1s). So there's some redundancy of information -- it would be possible to free up the bits from the resolution field and take the reserved bits and get one or two more resolutions packed into the H3 index (more on this in a bit).

This would definitely also require a new mode to represent it separately from the currently valid H3 indexes, which should not be broken, but if you take both sets of 3 bits to get two extra resolutions we would not be able to create a similarly restructured directed edge index (indexing the traversal from one h3 index to a neighbor), while if we take only the bits from the resolution field we could add a directed edge mode for these newer, finer grained indexes.

Is it worth the churn to the API to do this for a single extra resolution? That I am far less certain about. Since GPS can't resolve that accurately, we would really like to know what your use-case is for something like this before pushing forward on one of the solutions listed above (or something similar but different; one I didn't talk about was an "index modifier" index, such that the first 64-bits is a valid H3 index as currently defined while a modifier index has a special mode set and implies that it affects the prior index in the array -- this still has all of the indexing downsides of the greater-than-64-bit indexing, but at least the first 64-bit integer would be considered a valid index by existing code and if it just filters out "invalid" indexes, you'll still get partial precision out of the actual set of locations you're encoding).

**Comment by dfellis** [comment]
@isaacbrodsky @nrabinowitz You two are effectively the steerers of this project now, would definitely like your thoughts on this.

@datamacgyver I forgot to ask: can you tell us more about why you need a finer resolution?

**Comment by sahrk** [comment]
> So the subdivision algorithm could go all the way to the planck length and not really have any issues

To go significantly higher resolution you would likely need to switch to `long double` for all floating point representations and operations. That has some potential issues: the C standard doesn't require `long double` to actually be more precise than `double`; there might be a performance hit; and it might affect portability if there are languages that don't support more precise floating point representations. It's also possible there are places where integer overflow might occur at higher resolutions, requiring you to go to `long int`. This could have similar issues as going to `long double`.

@datamacgyver the short answer is probably that this task might be a bit much for "someone with pretty basic C". :)

**Comment by nrabinowitz** [comment]
My thoughts here:

- This would introduce a significant amount of complexity for what I'd guess is a very small number of use cases.
- We'd likely run into greater FPE concerns at the finer resolutions. We already have bugs after res 12 for certain algos that compare lat/long points.
- I doubt that there's a significant benefit to using H3 for this - the fine resolution areas are no longer truly geographical, don't actually require spherical geometry, and won't get the benefits of the standard H3 index format.

I'd guess that most use cases that need res > 15 should actually be using two coordinate systems - a fine coordinate system based on a cartesian grid, and H3 to geolocate the origin of the fine coordinate system. E.g. an address might look like `<h3index, i, j>` where `i, j` are the 2D coords of a regular hexagon grid of fixed edge length with 0,0 at the  `h3index` center. At fine zoom levels, assuming limited area, the difference between a cartesian grid and a geo grid should be negligible, and a cartesian grid is fairly easy to implement in the language of your choice.

**Comment by dfellis** [comment]
> > So the subdivision algorithm could go all the way to the planck length and not really have any issues
> 
> To go significantly higher resolution you would likely need to switch to `long double` for all floating point representations and operations. That has some potential issues: the C standard doesn't require `long double` to actually be more precise than `double`; there might be a performance hit; and it might affect portability if there are languages that don't support more precise floating point representations. It's also possible there are places where integer overflow might occur at higher resolutions, requiring you to go to `long int`. This could have similar issues as going to `long double`.
> 
> @datamacgyver the short answer is probably that this task might be a bit much for "someone with pretty basic C". :)

I forgot that we eliminated the long doubles from the code. :/

**Comment by datamacgyver** [comment]
Wow guys! I was just curious but they are some really thoughtful comments, much appreciated! I definitely think my eyes are bigger than my belly in terms of trying to do any of that in C (maybe one for the "future projects" list!) but I will think upon your suggestion @sahrk.

In answer to your use-case question, it's an interesting one! I work in agriculture so we have data collected by expensive GPS rigs on tractors, often helped by user base stations or transmitting systems. The leaflets say you can do 10s of cm with some kit. On top of that we have things like applicators that will tell you what's being sprayed from each nozzle of the tractor as it drives along,  cool stuff but a challenge to make sense of. 

For analysis and mapping we are evaluating a few different tools but, given the investment in getting something running, I thought I'd make sure I'd dug into everything I need to. Definitely don't break your system for my sake but, as I say, I really appreciate the thoughts!

**Comment by nrabinowitz** [comment]
Closing this, as we're not likely to take further action on it, but thanks for bringing up the use case!

**Comment by sahrk** [comment]
@datamacgyver if you need a higher resolution hexagonal global grid you might want to look at **[DGGRID](https://github.com/sahrk/DGGRID)**. Feel free to contact me if you have any questions.

**Comment by dimaqq** [comment]
A business use case for higher resolution: zooming in onto a shelf of products in a shop.
`.5m` edge is suddenly a little large. Doable, but a bit large.
