### ISSUE TITLE
h3_polyfill option for additional outer ring

### ISSUE THREAD

**Issue by ringhilterra** [uber/h3#332]
When using h3_polyfill (postgres), the fill stops 1 ring short of covering the full polygon (in red which I create from the points). It would be ideal if there was an option to have the polyfill return +1 additional ring of hexagons so that everything is covered.

Are there any alternative ways currently to add an additional ring for this use case?

![Screen Shot 2020-04-23 at 10 42 38 AM](https://user-images.githubusercontent.com/3506706/80131585-4d0f9980-854f-11ea-9666-1ccf39365be5.png)

**Comment by dfellis** [comment]
It fills by centerpoint, such that two contiguous polygons will also have contiguous h3 indexes without overlap.

If you want any hexagon that intersects the polygon, you need to offset the polygon by the h3 edge length at the given resolution you're filling.

We do have on the roadmap for H3 4.0 [to support multiple polyfill styles](https://github.com/uber/h3/issues/275) but it's a breaking API change so we're batching it up with other breaking changes. In the meantime you need to preprocess your polygon and apply the offset. [There are several algorithms and many existing libraries to do this in various languages](https://stackoverflow.com/questions/1109536/an-algorithm-for-inflating-deflating-offsetting-buffering-polygons) so hopefully you don't need to do it from scratch.

**Comment by ringhilterra** [comment]
makes sense, thanks for the response. I will close out this issue.

**Comment by parsaaes** [comment]
@dfellis It can be done by applying the KRing function (k=1) to every hexagon as an another temporary solution. Am I right? And is there a timeline for releasing v4?

**Comment by dfellis** [comment]
> @dfellis It can be done by applying the KRing function (k=1) to every hexagon as an another temporary solution. Am I right? And is there a timeline for releasing v4?

On your first question, no, applying a k-ring will overfill instead. (In the image at the beginning of this issue, the hexagon in the top-left corner would bring in 4 hexagons that don't even touch the polygon at all if you also added all of the neighbors that way.) You really would need to add a border to the polygon equal to the edge length of the hexagons.

On the second question we honestly don't have a timeline, and some work that could be done backwards compatible with the current v3 API crops up every month or so and they have been given higher priority to get out before we make the breaking changes. But that is expected to be ending *soon.*

**Comment by parsaaes** [comment]
> > @dfellis It can be done by applying the KRing function (k=1) to every hexagon as an another temporary solution. Am I right? And is there a timeline for releasing v4?
> 
> On your first question, no, applying a k-ring will overfill instead. (In the image at the beginning of this issue, the hexagon in the top-left corner would bring in 4 hexagons that don't even touch the polygon at all if you also added all of the neighbors that way.) You really would need to add a border to the polygon equal to the edge length of the hexagons.
> 
> On the second question we honestly don't have a timeline, and some work that could be done backwards compatible with the current v3 API crops up every month or so and they have been given higher priority to get out before we make the breaking changes. But that is expected to be ending _soon._

Thank you. You're right, this solution just overfills the polygon.
I guess many requirements can be fulfilled with just overfilling for now.

**Comment by parsaaes** [comment]
Another point I came up with is that applying KRing to every hexagon of polyfill's result doesn't always overfill the polygon because the polygon might not have any center points in it. Check this example image. Applying polyfill to the blue polygon results in an empty list.
![overfill](https://user-images.githubusercontent.com/32741675/92610956-8877ee00-f2cd-11ea-8062-ef3b45218581.png)

**Comment by dfellis** [comment]
Well, that polygon is significantly smaller than the grid itself, so that makes sense.

This issue is similar to the [Nyquist sampling frequency](https://en.wikipedia.org/wiki/Nyquist_frequency) where you need samplingffrequency to be slightly greater than twice the frequency of the underlying waveform you are trying to reproduce.

Since centerpoint containment is similarly regular in sampling the polygons on the planet, it also needs the grid to be smaller than the polygons in order to reasonably approximate them.

I don't have any good formula for this assertion, though.

**Comment by chninja** [comment]
> It fills by centerpoint, such that two contiguous polygons will also have contiguous h3 indexes without overlap.
> 
> If you want any hexagon that intersects the polygon, you need to offset the polygon by the h3 edge length at the given resolution you're filling.
> 
> We do have on the roadmap for H3 4.0 [to support multiple polyfill styles](https://github.com/uber/h3/issues/275) but it's a breaking API change so we're batching it up with other breaking changes. In the meantime you need to preprocess your polygon and apply the offset. [There are several algorithms and many existing libraries to do this in various languages](https://stackoverflow.com/questions/1109536/an-algorithm-for-inflating-deflating-offsetting-buffering-polygons) so hopefully you don't need to do it from scratch.

I am wondering how a apply an offset to a polygon. Does anybody know ? Thanks.

**Comment by Stophface** [comment]
If you are writing in JavaScript, you can use turf.js. It offers a buffer function https://turfjs.org/docs/#buffer.
Use the zoom level of h3 and the corresponding edge length https://h3geo.org/docs/core-library/restable/ to determine the offset of the buffer. But: this is very costly for polygons that are comples, large, have islands (such as countries like indonesia), ...  It would be very nice to be able to set a flag, allowing to choose how many "outer rings" one wants to add with h3. Since this library is so performant, it would be a shame if one would have to add a buffer at high costs...
