### ISSUE TITLE
Implement cellAreaKm2 and cellAreaM2

### ISSUE THREAD

**Issue by nrabinowitz** [uber/h3#350]
`cellAreaKm2` and `cellAreaM2` would return the actual area of the passed-in cell.

This should be based on the area of the spherical polygon based on the spherical model with WGS84 authalic radius.

**Comment by jswien** [comment]
This would be awesome to have, as it would be useful for converting count metrics to spatial densities.

**Comment by ajfriend** [comment]
Do we have code that we've used in the past for computing area, like for the average area table? Or at least, what would the method be for computing the area?

I was trying to work this out the other day, and couldn't quite crack it. My thought was to use the center point to break the hex up into triangles, and then compute the area of those spherical triangles based on some (average?) radius. Does that sound right?

**Comment by sahrk** [comment]
> Do we have code that we've used in the past for computing area, like for the average area table? 

The average area table was created by dividing the earth surface area by the number of hexes (adjusted for the 12 pentagons). So that won't do it...

> Or at least, what would the method be for computing the area?
> 
> I was trying to work this out the other day, and couldn't quite crack it. My thought was to use the center point to break the hex up into triangles, and then compute the area of those spherical triangles based on some (average?) radius. Does that sound right?

If we want the actual area of individual cells, then that won't be very accurate. There are spherical polygon area algorithms out there, but in this case I think it would be easiest to just break the hex into triangles as you suggest, and then find the spherical area of each triangle. The area of a spherical triangle is equal to the spherical excess **E**, which can be found using L’Huilier’s Formula (copied from [this random site](https://www.math.ucla.edu/~robjohn/math/spheretrig.pdf)):

![3FE84264-B3FA-4758-87E3-C22F2373CEC7_4_5005_c](https://user-images.githubusercontent.com/13046432/82358889-ffeede00-99bb-11ea-9d17-fd448635210d.jpeg)

**Comment by jswien** [comment]
I think the careful way to do it is to integrate the area two-form `r^2 sin(theta)` in spherical coordinates over the region of the hexagon. This sounds messy, and I think it's how the formula for triangles was derived in the first place. Probably best to break the hexagon into triangles and use that formula.

**Comment by jswien** [comment]
Actually, since lat/lng is just spherical coordinates this might be easier than one would think. Breaking the hex up and doing the integral creatively is the hard part. Let me think on it a bit more.

**Comment by ajfriend** [comment]
I played with the math a bit, and I think I got some functions working (in Python): https://gist.github.com/ajfriend/5b71b2ef3872e84506a4679bfb40a458

However, if I use the new `cell_area` function to get the average area of res 0 **hexagons**, it disagrees with the number reported by `h3.hex_area(0)`.

I'm not sure where the disagreement is.

**Comment by nrabinowitz** [comment]
> I'm not sure where the disagreement is.

I'd bet that the "earth surface area" @sahrk used was based on a non-spherical model of the earth, and you're using a spherical model. The discrepancies here will be largest at the res 0 level, and I assume increasingly negligible as the resolution gets finer.

**Comment by sahrk** [comment]
> I'd bet that the "earth surface area" @sahrk used was based on a non-spherical model of the earth

No, I just used a sphere. However, it looks like the new `cell_area` function is using an earth radius of 6371.0088 km, which is different than the radius I used, which was 6371.007180918475 km (the constant `EARTH_RADIUS_KM`). Depending on the magnitude of the discrepancy that could be the problem.

**Comment by nrabinowitz** [comment]
> > I'd bet that the "earth surface area" @sahrk used was based on a non-spherical model of the earth
> 
> No, I just used a sphere. 

I suppose I could have asked 😄

**Comment by ajfriend** [comment]
I don't think it's that. The difference I'm seeing is more significant than the difference in the radii constants.

|                method                | avg *hexagon* area, km^2 |
|--------------------------------------|--------------------------|
| `cell_area`, `R = 6371.0088`         | `4357451.630819806`      |
| `cell_area`, `R = 6371.007180918475` | `4357449.416078386`      |
| `h3.hex_area(0)`                     | `4250546.848`            |

**Comment by dfellis** [comment]
@ajfriend are you including or excluding pentagons? I think `hex_area` is just using the number of cells per resolution, which includes the 12 pentagons, in their area calculation.

If I'm right, if you adjust `hex_area` to use the number of cells in the resolution *minus 2* (each pentagon loses 1/6th of the area of a hexagon and there are 12 of them) it'll make the larger correction here. It would also explain why res 0 shows the largest discrepancy.

**Comment by ajfriend** [comment]
@dfellis My understanding of the `hexAreaKm2` function was that it **excludes pentagons**:

https://github.com/uber/h3/blob/c2fcb55d9914bbebd707e936d89de07c8b4e0aea/src/h3lib/include/h3api.h.in#L258-L259

And that's what I'm doing in the gist:

<img width="406" alt="Screen Shot 2020-07-30 at 12 54 14 PM" src="https://user-images.githubusercontent.com/984039/88968201-d7a91880-d263-11ea-879e-55b79247ecd1.png">

**Comment by dfellis** [comment]
That's what the comment says, but it may not be doing that, or doing it incorrectly?

I'm digging into the implementation now.

**Comment by dfellis** [comment]
Whelp.

https://github.com/uber/h3/blob/f621d07cbf15c3b78243b429f24eca009bdb1f13/src/h3lib/lib/geoCoord.c#L269-L276

It looks like it was done in some analysis in the past and then hardwired in the codebase...

**Comment by dfellis** [comment]
I say we go with the radius constant @sahrk pointed out which is already used elsewhere in the codebase and your Python notebook analysis code for new values, and *reference* that Python notebook in the codebase so our future selves can check it for correctness the next time this question comes up.

How does that sound @ajfriend ?

**Comment by ajfriend** [comment]
Yeah, that sounds good.

I was mostly using the notebook to see if I could get a calculation working *correctly*, and then my plan was to translate that logic to a function in the C library. If everyone signs off on the C lib version and we're pretty sure it is correct, I would expose that function to the Python library, and then write a much shorter notebook to compute the table. How's that sound, @dfellis?

**Comment by dfellis** [comment]
That sounds reasonable to me, but I am concerned that the trail ends there. @isaacbrodsky do you happen to know where these area numbers came from? It would be nice to be able to check their derivation against @ajfriend 's work.

**Comment by ajfriend** [comment]
It sounds like @sahrk did the original work. @sahrk, do you have the original calculations somewhere we could take a look at?

**Comment by sahrk** [comment]
> It sounds like @sahrk did the original work. @sahrk, do you have the original calculations somewhere we could take a look at?

Well, I'll bet somewhere on the MacBook Uber loaned me is a C program that generated that table, but @dfellis is correct: all I did was divide the area of a sphere by the specified resolution number of cells minus 2 (to account for the fact that 12 of them are pentagons). I just tried it in `bc` and got the same answer to 2 decimal places:

    pi=4*a(1)
    r=6371.007180918475
    (4*pi*r*r)/(122 - 2)
    4250546.845549762

**Comment by dfellis** [comment]
Hmm.. I wonder if it's a definition difference? If we take the area of the earth, subtract the area of those 12 pentagons, and then divide that by 110 (for all of the hexagons only) do we get @ajfriend 's number?

Because technically those 12 pentagons, even if we add back the 1/6th of missing "area" to be hexagons, would be smaller than every other hexagon because of the gnomonic projection distortion being maximized within them.

**Comment by sahrk** [comment]
> Hmm. I wonder if it's a definition difference?

@dfellis that makes sense; my reasoning was faulty. It would have only been correct if the cells were equal area, which of course they're not. Sorry Uber! I think I'm up to 4 bugs now...

**Comment by dfellis** [comment]
> > Hmm. I wonder if it's a definition difference?
> 
> @dfellis that makes sense; my reasoning was faulty. It would have only been correct if the cells were equal area, which of course they're not. Sorry Uber! I think I'm up to 4 bugs now...

By that comment I meant that it's actually a bit unclear what the "right" answer is there. If we unfolded the dymaxion-oriented icosahedron and then assigned some of the "missing pieces" in some pentagons to other pentagons to make them hexagons and removed them from the map otherwise, then those hexagons *would* be assigned the correct sizing by that algorithm. (It would be a bit weird to have some coordinates jump across the world, but if your data is primarily land-only, not that big of a deal.)

If we take the name "hexArea" literally, then excluding these pentagons is the right call. If we want to use the area of arbitrary geopolygons to estimate the number of hexagons we need, then your's is best because we are less likely to underestimate the needed number.

I think @ajfriend 's work to have the actual area calculation for a given H3 index will make it easier for people to make their own determination that is best for them, and can also produce more accurate averages for their local position on the planet.

**Comment by sahrk** [comment]
> > > Hmm. I wonder if it's a definition difference?
>>
> > @dfellis that makes sense; my reasoning was faulty. It would have only been correct if the cells were equal area, which of course they're not. Sorry Uber! I think I'm up to 4 bugs now...
> 
> By that comment I meant that it's actually a bit unclear what the "right" answer is there. If we unfolded the dymaxion-oriented icosahedron and then assigned some of the "missing pieces" in some pentagons to other pentagons to make them hexagons and removed them from the map otherwise, then those hexagons _would_ be assigned the correct sizing by that algorithm.

I think I see what you're saying, and like the idea that the average should somehow take into account the pentagons. But I'm not sure that salvages my math. You can't actually make planar hexagons that correspond to spherical hexagons by re-arranging parts of pentagons, so it feels to me like you're in effect adding area to the numerator of the area average when you create such a hexagon. Maybe @ajfriend could generate a table of pentagon area at each resolution, and we could compare the options?

> If we take the name "hexArea" literally, then excluding these pentagons is the right call. 

Agreed. Pentagon area at each resolution from @ajfriend would enable that. 

> If we want to use the area of arbitrary geopolygons to estimate the number of hexagons we need, then your's is best because we are less likely to underestimate the needed number.

I feel a little uncomfortable about that; it might be better to generate the best value possible and add an explicit nudge when it's warranted by an algorithm. Especially if my math really is off, in which case I'd at least like to see the table in the documentation corrected.

**Comment by dfellis** [comment]
> > > > Hmm. I wonder if it's a definition difference?
> > > 
> > > 
> > > @dfellis that makes sense; my reasoning was faulty. It would have only been correct if the cells were equal area, which of course they're not. Sorry Uber! I think I'm up to 4 bugs now...
> > 
> > 
> > By that comment I meant that it's actually a bit unclear what the "right" answer is there. If we unfolded the dymaxion-oriented icosahedron and then assigned some of the "missing pieces" in some pentagons to other pentagons to make them hexagons and removed them from the map otherwise, then those hexagons _would_ be assigned the correct sizing by that algorithm.
> 
> I think I see what you're saying, and like the idea that the average should somehow take into account the pentagons. But I'm not sure that salvages my math. You can't actually make planar hexagons that correspond to spherical hexagons by re-arranging parts of pentagons, so it feels to me like you're in effect adding area to the numerator of the area average when you create such a hexagon. Maybe @ajfriend could generate a table of pentagon area at each resolution, and we could compare the options?

If you literally took the 5 triangular "slices" from, say, the "polar" pentagons and redistributed them in a predictable way to the two rings of "equatorial" pentagons, you wouldn't be adding area, you'd just cause data near the north and south pole to sometimes show up neighboring other places around the planet. We had considered such a thing before reaching out to you because we didn't really like it, but such a solution makes consuming hex-binned data in gigantic matrices easier, as we can have a global IJ coordinate system underneath it (even if sometimes nonsensical around icosahedron boundaries).

> 
> > If we take the name "hexArea" literally, then excluding these pentagons is the right call.
> 
> Agreed. Pentagon area at each resolution from @ajfriend would enable that.

Talking to @ajfriend it looks like his python prototype works perfectly well for that, too.

> 
> > If we want to use the area of arbitrary geopolygons to estimate the number of hexagons we need, then your's is best because we are less likely to underestimate the needed number.
> 
> I feel a little uncomfortable about that; it might be better to generate the best value possible and add an explicit nudge when it's warranted by an algorithm. Especially if my math really is off, in which case I'd at least like to see the table in the documentation corrected.

It was a bit of a reach, but the point I was trying to make was just that these are all trade-offs determined by the particular application and it would be beneficial there, and if you consider the `hexArea` to have just been not a great name for the cells that the H3 index represents, it isn't that bad since it gets closer to the average including the pentagons.

In the opposite direction, there are some applications where the average hexagon area including only hexagons for the planet is worthless since the area distortion can get up to about 2x difference between the extremes but the *localized* distortion is much smaller, such as within a single city. I'm not at Uber anymore, but I suspect this `cellArea` task is for precisely such a need.

Anyways, I don't think this should be too embarrassing. It's impossible to not make mistakes, but the systems we put in place should try to help us avoid, or at least mitigate, them. We should've spotted the hardwired values and requested the algorithm that generated them. I don't know if we would've understood at that time the implications of splitting up two of the pentagons to turn the rest into hexagons in the calculation, but it would have probably helped here, and we might have picked up on the implications earlier.

**Comment by ajfriend** [comment]
So I've got a few more mysteries that I'm working through here: https://github.com/uber/h3-py/blob/area/play_area.ipynb
Let me know if you can see where I'm messing up my math!

First, I wanted to see if there was a constant ratio between resolutions when looking at average pentagon area, but that doesn't seem to be the case:

<img width="521" alt="Screen Shot 2020-08-01 at 3 13 44 PM" src="https://user-images.githubusercontent.com/984039/89111348-a23e2f80-d409-11ea-8ed3-0d047bbf2334.png">

The ratio also is not constant for average hexagon area, but the effect is smaller because there are more hexagons:

<img width="522" alt="Screen Shot 2020-08-01 at 3 14 20 PM" src="https://user-images.githubusercontent.com/984039/89111360-c13cc180-d409-11ea-9aaf-563327f2cc40.png">

Unsurprisingly, then, we get that the ratio between the average hexagon area and the average pentagon area changes across resolutions:

<img width="542" alt="Screen Shot 2020-08-01 at 3 15 16 PM" src="https://user-images.githubusercontent.com/984039/89111377-ed584280-d409-11ea-958a-10c699e44c81.png">

So now I'm thinking to myself, "How am I going to get an accurate table for average hexagon area if there isn't a constant ratio?". I can't just compute the raw hexagon areas and sum them, as higher resolutions have *waaay* too many hexagons for that to be computationally feasible.

So I came up with a plan: For each resolution, compute the **total earth area**, subtract the area of the **12 pentagons** at that resolution, and divide that by the number of **hexagons** at that resolution.

However, there's **a bug somewhere**, as I'm getting inconsistent results between this "implied" average hex area, and the "actual" hex area when looking at the first few resolutions:

<img width="601" alt="Screen Shot 2020-08-01 at 3 24 05 PM" src="https://user-images.githubusercontent.com/984039/89111473-11685380-d40b-11ea-98c0-8bcd0697fff9.png">

Well, actually, resolution 0 is OK, but there's definite disagreement after that.

There must be a bug somewhere in my code, since the area of the Earth should add up properly, but I can't seem to spot it today. The code should be the same as what I have above, but, for reference: https://github.com/uber/h3-py/blob/area/src/h3/_cy/unstable_area.pyx

I'll probably take a look at this again in a few days. Let me know if you see where I'm messing up before then!

**Comment by ajfriend** [comment]
Ah, `num_hexagons` is wrong!

**Comment by ajfriend** [comment]
...and I had the same mental-model error in the code to get all the *hexagons* at a resolution. It should have been:

```python
def hexes_at_res(res):
    cells = h3.get_res0_indexes()
    cells = h3.uncompact(cells, res)

    hexes = cells - h3.get_pentagon_indexes(res)
    
    return hexes
```

**Comment by ajfriend** [comment]
If [everything here is right](https://github.com/uber/h3-py/blob/area/area_table.ipynb) (I think it is...) then here's the new area table:

|   Res |   Average <ins>Hexagon</ins><br>Area (km^2) |   Pentagon Area* (km^2) |    Ratio |
|------:|--------------------------------------------:|------------------------:|---------:|
|     0 |                         4,357,449.416078384 |     2,562,182.162955495 | 0.588    |
|     1 |                           609,788.441794133 |       328,434.586246469 | 0.538604 |
|     2 |                            86,801.780398997 |        44,930.898497879 | 0.517626 |
|     3 |                            12,393.434655088 |         6,315.472267516 | 0.509582 |
|     4 |                             1,770.347654491 |           896.582383141 | 0.506444 |
|     5 |                               252.903858182 |           127.785583023 | 0.505273 |
|     6 |                                36.129062164 |            18.238749548 | 0.504822 |
|     7 |                                 5.161293360 |             2.604669397 | 0.504654 |
|     8 |                                 0.737327598 |             0.372048038 | 0.50459  |
|     9 |                                 0.105332513 |             0.053147195 | 0.504566 |
|    10 |                                 0.015047502 |             0.007592318 | 0.504557 |
|    11 |                                 0.002149643 |             0.001084609 | 0.504553 |
|    12 |                                 0.000307092 |             0.000154944 | 0.504552 |
|    13 |                                 0.000043870 |             0.000022135 | 0.504551 |
|    14 |                                 0.000006267 |             0.000003162 | 0.504551 |
|    15 |                                 0.000000895 |             0.000000452 | 0.504551 |

*: Within a given resolution, all pentagons have the same area.

**Comment by ajfriend** [comment]
# Hex Avg Area Table: New values vs. Old

|   Res |                 New |                 Old |   (N/O) Ratio |
|------:|--------------------:|--------------------:|--------------:|
|     0 | 4,357,449.416078384 | 4,250,546.848000000 |   1.025150309 |
|     1 |   609,788.441794133 |   607,220.978200000 |   1.004228220 |
|     2 |    86,801.780398997 |    86,745.854030000 |   1.000644715 |
|     3 |    12,393.434655088 |    12,392.264860000 |   1.000094397 |
|     4 |     1,770.347654491 |     1,770.323552000 |   1.000013615 |
|     5 |       252.903858182 |       252.903364500 |   1.000001952 |
|     6 |        36.129062164 |        36.129052100 |   1.000000279 |
|     7 |         5.161293360 |         5.161293200 |   1.000000031 |
|     8 |         0.737327598 |         0.737327600 |   0.999999997 |
|     9 |         0.105332513 |         0.105332500 |   1.000000127 |
|    10 |         0.015047502 |         0.015047500 |   1.000000127 |
|    11 |         0.002149643 |         0.002149600 |   1.000020064 |
|    12 |         0.000307092 |         0.000307100 |   0.999973545 |
|    13 |         0.000043870 |         0.000043900 |   0.999322732 |
|    14 |         0.000006267 |         0.000006300 |   0.994790656 |
|    15 |         0.000000895 |         0.000000900 |   0.994790656 |

**Comment by sahrk** [comment]
> If you literally took the 5 triangular "slices" from, say, the "polar" pentagons and redistributed them in a predictable way to the two rings of "equatorial" pentagons, you wouldn't be adding area, you'd just cause data near the north and south pole to sometimes show up neighboring other places around the planet. We had considered such a thing before reaching out to you because we didn't really like it, but such a solution makes consuming hex-binned data in gigantic matrices easier, as we can have a global IJ coordinate system underneath it (even if sometimes nonsensical around icosahedron boundaries).

The average of a set of cells, where all the cells have the same weight, would be:

    avgArea = totalOfAllCellAreas / numCells

If a pentagon “were actually” a hexagon, I think that it would have an area of `pentArea + (1/5 * pentArea) = 6/5 * pentArea`. So I think that `effectiveHexArea` would be:

    effectiveHexArea = (totalHexArea + totalPentHexArea) / numCells
                                  = (totalHexArea + (12 * (6/5 * pentArea)) / numCells 
                                  = (totalHexArea + 72/5 * pentArea) / numCells

I used that formula to add a column to the table generated by @ajfriend . I am not advocating that it be used anywhere, but share it just in case.

| Res | New | Old | Effective Hex Avg | 
|-----|------------------:|------------------:|------------------:|
| 0 | 4,357,449.41607838 | 4,250,546.848000000 | 4,231,269.335370340 | 
| 1 | 609,788.441794133 | 607,220.978200000 | 606,714.803718621 | 
| 2 | 86,801.780398997 | 86,745.854030000 | 86,734.691581177 | 
| 3 | 12,393.434655088 | 12,392.264860000 | 12,392.030971710 | 
| 4 | 1,770.347654491 | 1,770.323552000 | 1,770.318731377 | 
| 5 | 252.903858182 | 252.903364500 | 252.903265803 | 
| 6 | 36.129062164 | 36.129052100 | 36.129050058 | 
| 7 | 5.161293360 | 5.161293200 | 5.161293113 | 
| 8 | 0.737327598 | 0.737327600 | 0.737327593 | 
| 9 | 0.105332513 | 0.105332500 | 0.105332513 | 
| 10 | 0.015047502 | 0.015047500 | 0.015047502 | 
| 11 | 0.002149643 | 0.002149600 | 0.002149643 | 
| 12 | 0.000307092 | 0.000307100 | 0.000307092 | 
| 13 | 0.000043870 | 0.000043900 | 0.000043870 | 
| 14 | 0.000006267 | 0.000006300 | 0.000006267 | 
| 15 | 0.000000895 | 0.000000900 | 0.000000895 |

> Anyways, I don't think this should be too embarrassing. It's impossible to not make mistakes, but the systems we put in place should try to help us avoid, or at least mitigate, them. We should've spotted the hardwired values and requested the algorithm that generated them. I don't know if we would've understood at that time the implications of splitting up two of the pentagons to turn the rest into hexagons in the calculation, but it would have probably helped here, and we might have picked up on the implications earlier.

Thanks for the kind words @dfellis . I was being over-dramatic on the discovery of a 4-year old error in public. I'm actually really proud of the work we did on H3.

**Comment by sahrk** [comment]
> Here's the code: https://github.com/uber/h3-py/blob/area/area_table.ipynb
> 
> # Hex Avg Area Table: New vs. Old values
> Res	New	Old	(N/O) Ratio
> 0	4,357,449.416078384	4,250,546.848000000	1.025150309
> 1	609,788.441794133	607,220.978200000	1.004228220
> 2	86,801.780398997	86,745.854030000	1.000644715
> 3	12,393.434655088	12,392.264860000	1.000094397
> 4	1,770.347654491	1,770.323552000	1.000013615
> 5	252.903858182	252.903364500	1.000001952
> 6	36.129062164	36.129052100	1.000000279
> 7	5.161293360	5.161293200	1.000000031
> 8	0.737327598	0.737327600	0.999999997
> 9	0.105332513	0.105332500	1.000000127
> 10	0.015047502	0.015047500	1.000000127
> 11	0.002149643	0.002149600	1.000020064
> 12	0.000307092	0.000307100	0.999973545
> 13	0.000043870	0.000043900	0.999322732
> 14	0.000006267	0.000006300	0.994790656
> 15	0.000000895	0.000000900	0.994790656

This my have already been mentioned somewhere, but I think it would be helpful to users if the table also contained the minimum and maximum hex areas at each resolution. I'm thinking of algorithms like @dfellis was discussing above, where the user may need to bound a solution from above or below.

**Comment by ajfriend** [comment]
Agreed that min/max bounds for cell at each resolution would be useful. (We should think through if it's more useful to include/exclude pentagons, or provide both). 

However, the task to compute the min/max is a bit trickier than computing the average, I think. We'd have to do some kind of search at each resolution, and that search would need to be smart enough that we don't need to inspect *every* hexagon within a resolution. @sahrk, are you aware of any clever ways to do this?

We could maybe come up with a heuristic based on what we see in this notebook: https://observablehq.com/@fil/h3-oddities
If I'm reading that map correctly, the red hexes have the largest area.

<img width="1074" alt="Screen Shot 2020-08-03 at 2 20 31 PM" src="https://user-images.githubusercontent.com/984039/89228546-aa76a600-d594-11ea-859e-15742d3a9303.png">

**Comment by sahrk** [comment]
> Agreed that min/max bounds for cells at each resolution would be useful. (We should think through if it's more useful to include/exclude pentagons, or provide both).

I vote for having the min/max actual hexagon area, with the pentagon area as a separate column (unless you're considering something like the "effective cell area" from my earlier comment, in which case I'd have to rethink my answer).

> However, the task to compute the min/max is a bit trickier than computing the average, I think. We'd have to do some kind of search at each resolution, and that search would need to be smart enough that we don't need to inspect _every_ hexagon within a resolution. @sahrk, are you aware of any clever ways to do this?
> 
> We could maybe come up with a heuristic based on what we see in this notebook: https://observablehq.com/@fil/h3-oddities
> If I'm reading that map correctly, the red hexes have the largest area.
> 
> <img alt="Screen Shot 2020-08-03 at 2 20 31 PM" width="1074" src="https://user-images.githubusercontent.com/984039/89228546-aa76a600-d594-11ea-859e-15742d3a9303.png">

Not sure how clever but I believe that you are indeed reading that image correctly, and that the hexagons with the largest area are the ones in the middle of each triangle, i.e. `FaceIJK(anyFace, (0,0,0))`. They get smaller as distance increases from the center; the smallest hexagon would be the pentagon, if it were a hexagon. So the min will be one of the hexes adjacent to the pentagon, or at worst one adjacent to those; I'm hedging because some of the cells will be split by an icosahedron edge and I'm uncertain the effect that has on their area. But your `cell_area` should allow you to scope out the situation near a pentagon at resolutions with each of the two possible grid orientations.

And a general comment: when doing any statistics on cells, remember that because of symmetry you only ever have to explore 1/12 of a single face, which is a triangle bounded by any two of the I, j, or k axes (see [this figure](https://h3geo.org/docs/core-library/h3ToGeoDesc)).

**Comment by ajfriend** [comment]
Functionality added in https://github.com/uber/h3/pull/377 and released in https://github.com/uber/h3/releases/tag/v3.7.0
