### ISSUE TITLE
h3ToGeoBoundary sometimes returns pentagon-ish blob with 10 points

### ISSUE THREAD

**Issue by ravenAtSafe** [uber/h3#418]
Coords (-5.24539, 2.30088) result in a resolution 15 index of `646055440295133184`.  Asking for the boundary of that index results in a poly that looks sort of like a pentagon but has too many points.  (See image below)

I think I've seen variations where all the child indexes result in the same boundary as the parent, and you can't really get the parent of the parent either.  Possibly index 583009443558457343 but haven't double checked just yet.

We believe we've confirmed similar behavior in the JavaScript H3 library, so reasonably sure we didn't botch the integration.  Is there a bug, or are we doing something very wrong?

![image](https://user-images.githubusercontent.com/9891443/103713591-98e56000-4f71-11eb-9533-c24366c7beed.png)

**Comment by nrabinowitz** [comment]
This is expected behavior - see https://stackoverflow.com/a/60729633/380487 for more details. Cells whose edges cross the edges of the icosahedron the grid is based on get additional distortion vertexes inside of those edges. We still refer to these cells as "hexagons" or "pentagons" as they still have 6 or 5 topological neighbors.

> I think I've seen variations where all the child indexes result in the same boundary as the parent, and you can't really get the parent of the parent either. Possibly index 583009443558457343 but haven't double checked just yet.

Due to the shape of hexagons in the grid, no cell's children will exactly match its boundary - there's some explanation here: https://h3geo.org/docs/usecases . The difference between children and parent always falls within a fixed margin of error.

**Comment by ravenAtSafe** [comment]
Interesting!  Thank you for the explanation.
