### ISSUE TITLE
Broken link in docs

### ISSUE THREAD

**Issue by dmatranga** [uber/h3#434]
In the Overview doc, located at [https://github.com/uber/h3/blob/master/docs/core-library/overview.md](https://github.com/uber/h3/blob/master/docs/core-library/overview.md), there is a broken link to a page that lists the resolutions and average cell area for each: 

_"A table detailing the average cell area for each H3 resolution is available **here**."_

**Comment by nrabinowitz** [comment]
The issue here is the `.md` extension - the file is here: https://github.com/uber/h3/blob/master/docs/core-library/restable.md 

The docs are used to produce the website, and the link [works properly on the website](https://h3geo.org/docs/core-library/overview), where the `.md` extension is part of the path. As the website, not the Github rendering of the docs, is the canonical documentation location, I think this is probably a WONTFIX.

**Comment by dmatranga** [comment]
Got it, thanks for the tip!
