### ISSUE TITLE
Use `PointerAlignment: Right` in `.clang-format`

### ISSUE THREAD

**Issue by ajfriend** [uber/h3#467]
Would we want something like this, to try to consistently keep the `*` with the variable name instead of the type?

```
DerivePointerAlignment: false
PointerAlignment: Right
```

Apparently, if you leave `DerivePointerAlignment` enabled, the formatter takes the most common convention in any given file: https://clang.llvm.org/docs/ClangFormatStyleOptions.html

**Comment by dfellis** [comment]
I think this is a good idea and that default is bonkers.

(I personally think the pointer star should stick to the type because I see it as part of the type signature: it's not `N` bytes for that type you declared, it's the size of a pointer on your system, which is probably 64-bits / 8-bytes, but I know the vast majority of C devs disagree with me on this, so let's just go with the standard convention.)
