### ISSUE TITLE
Rename `experimentalH3ToLocalIj`, etc.

### ISSUE THREAD

**Issue by ajfriend** [uber/h3#475]
Relating to:

- experimentalH3ToLocalIj
- experimentalLocalIjToH3
- h3ToLocalIj.c
- testH3ToLocalIj.c
- localIjToH3.c
- ...and a few other places

Possible changes:

- drop `experimental` from the name
- use `cell` instead of `h3`
- update filters

**Comment by dfellis** [comment]
Weren't they called "experimental" because we have issues crossing multiple icosahedron faces with the current algorithm, but that it could be possible to resolve? Did we find a solution?

**Comment by nrabinowitz** [comment]
To my knowledge we did not find a solution here - we have a solution for `gridPathCells` and `gridDistance`, which also rely on an unfolded planar coordinate approach, but not for these. I think the other reason to call these `experimental` was so that users would not rely on the output - the idea was that you'd get `i,j` coords that would be symmetrical with the two functions, but that later versions of H3 might change the origin, etc of these coords.
