### ISSUE TITLE
version GLIBC_2.14 not found 

### ISSUE THREAD

**Issue by thesong513** [uber/h3#493]
version GLIBC_2.14 not found ;
i con not update GLIBC, Is there any other solution？
thanks a lot

**Comment by isaacbrodsky** [comment]
Could you paste what command you ran which gave this error, and the output from that command? As well as the operating system version being used?

In general H3 should be able to use older versions or alternate libc's without too much trouble. You may need to compile H3 for your system if it does not use glibc.

**Comment by thesong513** [comment]
I just used the h3 in spark with scala, and the code runs normally on this machine with win10, but it runs error in cluster.
There is the error information. 
java.lang.UnsatisfiedLinkError: ....../lib64/libc.so.6: version "GLIBC_2.14" not found required by ..... libh3-javaxxxx.so

**Comment by isaacbrodsky** [comment]
Sorry for the delay responding. The issue here is probably that your cluster is running an operating system that is not using a recent version of GLIBC (such as Alpine Linux that uses musl). H3-Java does not distribute prepackaged binaries for that configuration, but it should be possible for you to find out what configuration you need from your cluster administrator, and then compile h3-java for that. (i.e. run `mvn package` on uber/h3-java)
