### ISSUE TITLE
What is a proper way to convert a GeoJSON linestring to a set of H3 hexagons?

### ISSUE THREAD

**Issue by gtitov** [uber/h3#569]
Not sure if it is a question or a feature request but I faced some difficulties converting a line to a set of H3 hexagons.

I haven't found a dedicated function for that and I came up with an algorithm where I

1. extract points from a line
1. calculate an H3 hexagon of these points (`geo_to_h3` in h3-py)
1. connect the pairs of H3 hexagons (`h3-line` in h3-py)
1. concatenate the pair paths removing duplicating hexagons

I wonder if there is a better way to do the conversion? I was looking for something like [gdal_rasterize](https://gdal.org/programs/gdal_rasterize.html).

**Comment by nrabinowitz** [comment]
Your approach is what I would have recommended. `h3_line` has some limitations here - it's describing a path between two cells, so it may not overlap perfectly with the line it's representing. The only guarantees it offers are 1) the path it returns is the shortest path (though there may be many shortest paths of equal length) and 2) each successive cell touches the previous cells but none of the cells in the line before that. The shortest path guarantee usually means that `h3_line` follows great arcs rather than cartesian lines, which may or may not be what you need.

If you want to make sure that the line is *covered* by H3 cells, you might try e.g. sampling indexes along the length of the line, buffering them by 1, and then removing indexes that the line does not intersect. This is a much more expensive operation than `h3_line`, but it would ensure that the line is fully covered.

**Comment by sahrk** [comment]
> …The shortest path guarantee usually means that `h3_line` follows great arcs rather than cartesian lines, which may or may not be what you need.

Just to clarify, within each icosahedron face the grid shortest path will follow a great circle arc, which maps to a cartesian line in the H3 projection. If you want to precisely capture a great circle arc/line that crosses icosahedron edges, you would need to break-up the original arc/line wherever it intersects an edge, and then perform your algorithm on each of the resulting line segments.

**Comment by gtitov** [comment]
Thank you very much for the answer and for the useful comment! It quite clear now. Also I'm delighted to get an answer from major specialists like you!
