### ISSUE TITLE
exactEdgeLength returns 0 value for some hexes

### ISSUE THREAD

**Issue by jmoniatte** [uber/h3#605]
Some hexes return a 0 value for their edge length:

```javascript
// WORKS
const h = '115283473fffffff';
h3.exactEdgeLength(h, h3.UNITS.km);
// 10.294736086198531

// DOES NOT WORK
const hex = h3.geoToH3(45.535628, -122.658668, 11)
// 8b28f0004693fff
h3.h3IsValid(hex)
// true
h3.exactEdgeLength(h3, h3.UNITS.m)
// 0

// Area works for the same hex:
h3.cellArea(hex, h3.UNITS.m2);
// 1974.9105201719883
```

Note that this behavior is also present in a Ruby codebase.

**Comment by isaacbrodsky** [comment]
This is because `exactEdgeLength` expects an edge, not a cell. The upcoming version 4 of H3 should give a more informative error message that the index's mode is not what's expected.

In the mean time I'd suggested using either [`edgeLength`](https://h3geo.org/docs/api/misc#edgelengthm) (produces an average edge length at the resolution) or selecting one of the edges from [`getH3UnidirectionalEdgesFromHexagon[​](https://h3geo.org/docs/api/uniedge#geth3unidirectionaledgesfromhexagon)`](https://h3geo.org/docs/api/uniedge#geth3unidirectionaledgesfromhexagon) (produces an exact length for one of the edges)

**Comment by jmoniatte** [comment]
Awesome, thanks @isaacbrodsky for the very quick answer, makes sense.
