### ISSUE TITLE
H3 to parent returns wrong hexagon

### ISSUE THREAD

**Issue by vec12** [uber/h3#632]
When  I run `h3_to_parent('8a1e1b28e937fff', 7)` result is `871e1b28effffff`, and `8a1e1b28e937fff` hexagon is definitely not inside `871e1b28effffff` hexagon. 
If i run `h3.geo_to_h3(44.83484888199552, 20.402415688610017, 7)` (with `8a1e1b28e937fff` hexagon center) result is correct hexagon `871e1b281ffffff`
Using h3 for python, version 3.6.1

**Comment by dfellis** [comment]
No, that is the correct hexagon as `h3_to_parent` follows the hierarchical graph-based parent-child relationship, not the spatial one, [as demonstrated here](https://observablehq.com/@nrabinowitz/h3-hierarchical-non-containment?collection=@nrabinowitz/h3).

Because every finer resolution of a hexagon contains 7 hexagons with partial containment, there is a fractal-like change in the apparent shape of the original parent hexagon. This is a consequence of the imperfect containment of the finer hexagon grid within the coarser hexagon grid and is unavoidable with hexagons (you need squares or triangles for perfect hierarchical containment).

If you want the closest spatial containment rather than the grid hierarchy, a simple `h3.geo_to_h3(*h3.h3_to_geo(h3_id), 7)` will do what you desire.
