### ISSUE TITLE
How do I create a GTA-like circle area instead of hexagon area?

### ISSUE THREAD

**Issue by alexkokorin2** [uber/h3#68]
I'm using k-ring method and it returns a hexagon area. How can I nicely exclude some hexagons so it'll look like a circle? I'd probably have to `.filter`every hexagon based on its distance from a center (and convert lat, lon to km so I'll be able to use a desired radius). 
 
Does this issue rely on #23?

**Comment by nrabinowitz** [comment]
I don't think this is an H3 issue per se. `kRing` returns hexagons that are a given number of steps (i.e. edge traversals) from the origin, which due to the nature of a hexagon grid usually gives you a roughly hexagonal area. If you prefer a more circular shape, you either have to filter by distance as you suggest or create a circle-like polygon and use the `polyfill` method to get the hexagons within it.
