### ISSUE TITLE
Python H3 naming convention

### ISSUE THREAD

**Issue by hamiltoncj** [uber/h3#699]
I have worked with a number of major packages spanning different programming languages over the years and have come to the conclusion that it is a big mistake to use different function names for the different languages. I just found out that H3 changed the function names quite dramatically for v4. I use H3 in the Density Analysis plugin for QGIS and even though the python function names are more pythonic, please use the same names across all languages otherwise it becomes confusing and difficult to recode algorithms in one language into another. If you are making this big of a jump in naming make the python names the same as in the other languages. 

Others may disagree and want to keep a perceived "pythonic" naming convention, but they probably haven't been programming as long as I have and seen the difficulties this can create.

I will adapt to what ever you do, but this is just to express my words of wisdom however you may take it.

Thanks!

**Comment by ajfriend** [comment]
What version of h3-py are you referring to? We've released a beta version of 4.0 for Python.

As it's a beta, the names aren't finalized, so I'd love any feedback you may have!

The names should mostly be the same between C and Python, except that we use snake instead of camel case.

**Comment by hamiltoncj** [comment]
I was referring to the 4.0 beta. Because H3 is a library that spans multiple languages and having worked with other large libraries, my personal opinion is to use exactly the same function calls. When tutorials are written you don't need to distinguish between function calls for different languages. I know it is a preference to use snake instead of camel case for python, but I don't think you should do that in this case. For example for C, Java, and JavaScript you use latLngToCell, but for Python it is h3.latlng_to_cell. A Python purest would prefer the latter, but in the grand scheme of things that is not as important as having constancy across all languages. I think you should use the same function names across all languages.

**Comment by ajfriend** [comment]
I appreciate your input! I definitely consider user feedback when designing the API.

This is a matter of tradeoffs. I can see the benefit of having exactly the same function names across languages, but I also see the benefit of having Pythonic names. And the value of those features are probably different for different subgroups of users. Certainly, we want the names to be as similar as is reasonable to make the correspondence obvious for users.

Also, there are cases where exact name matches wouldn't make sense in a different language. For example we wouldn't have a `cellsToLinkedMultiPolygon` in Python, because we wouldn't expose a linked list data structure to a user; we would just give them a normal Python `list`.

So I lean strongly to keeping the names in snake case, but I am happy to hear other's opinions. I think that's the best outcome for the majority of `h3-py` users who are probably not working across languages. Also, honestly, I don't see having to mentally convert between snake case and camel case as that much of a burden compared to the other tradeoffs.

**Comment by hamiltoncj** [comment]
That was my preference, but know that others have different preferences so I will close this ticket.

**Comment by ajfriend** [comment]
Thanks. And I do appreciate you raising your preference!
