### ISSUE TITLE
About suitable H3 Resolutions

### ISSUE THREAD

**Issue by LaughXP** [uber/h3#71]
How to choose the suitable h3 resolutions when use `polyfill` ?

**Comment by dfellis** [comment]
That depends on the particular use-case you're interested in.

Any grid system like H3 or [S2](http://s2geometry.io/about/) is a discretization of your data and some precision is going to be lost* versus the original coordinates. I would recommend [looking at the table of resolution sizes](https://uber.github.io/h3/#/documentation/core-library/resolution-table) and decide which hexagon size is the best fit for you.

But the lowest resolutions are generally the least useful, since res 0 is roughly continental in size. Resolution 7 is the first resolution that seems useful for human-scaled applications, in my opinion.

Resolution 7: Roughly city-sized
Resolution 8: Roughly neighborhood-sized
Resolution 9: Roughly 2-4 city blocks in size (different cities have different block sizes)
Resolution 10: Less than a city block in size
...
Resolution 15: Coffee table-sized

(I haven't really used resolutions 11-14, either, because they're too fine grained for vehicle map data, but they would probably have useful applications for mapping the interior of a building.)

*: Actually resolution 15 of H3 produces hexagons smaller than the accuracy of almost all GPS units, and so could be considered a form of lossless compression of the data versus the floats required to define lat, lng

**Comment by nrabinowitz** [comment]
Answered here: https://stackoverflow.com/questions/50725530/how-to-choose-the-suitable-h3-resolutions-when-use-polyfill

**Comment by nrabinowitz** [comment]
Closing this now - please use StackOverflow for further discussion (trying to move this kind of question to that platform). Thanks!

**Comment by LaughXP** [comment]
@dfellis @nrabinowitz Thanks!
