### ISSUE TITLE
helping to integrate h3 to php

### ISSUE THREAD

**Issue by neatlife** [uber/h3#95]
I am wirting a php extension for h3: https://github.com/neatlife/php-h3, but when i call h3 function in php extension, it always report error like below:

![image](https://user-images.githubusercontent.com/4076198/42861740-f6d39182-8a8e-11e8-91b1-99101fb10269.png)

hope someone help me to fix this error, thanks.

**Comment by dfellis** [comment]
`degsToRads` is not the function you think it is. It converts degrees to radians, not (lat, lng) coordinates + resolution to hexagon IDs. You want `h3ToGeo` instead.

As for the error you're running into, I'm not sure if that's because the signature doesn't match (`degsToRads` only takes one `double`, not two `double`s and an `int`) or if your `.so` file cannot be loaded because you're on a Mac (I think the standard there is `.dylib`; `.so` is the Linux file and `.dll` for Windows)

**Comment by isaacbrodsky** [comment]
@neatlife could you post the following?
* output of `uname -a`
* output of `file path_to_your_h3.so`
* output of `nm path_to_your_h3.so` (if you're using Mac OSX)

Other than the naming issue @dfellis mentioned above, my guess is that this is happening because PHP is not loading the built H3 library, only your extension (which needs to statically include H3 or needs to find H3 dynamically) You could try using `make install` after building the Uber H3 library and see if that helps.

**Comment by neatlife** [comment]
@dfellis Yes, you are right, i already fix nameing error: https://github.com/neatlife/php-h3/commit/fcc9324620009647339cc7059d5df78d9dee2044

**Comment by neatlife** [comment]
@isaacbrodsky Yes,  of course

![image](https://user-images.githubusercontent.com/4076198/42915202-fab76b96-8b30-11e8-9ca8-1fc8d4eb5239.png)

before write php extension, I already execute cmake and make and sudo make install command in h3 project

**Comment by isaacbrodsky** [comment]
One other thing I forgot to mention is running `otool -L your_path_to_h3.so`

Is the H3 library installed at `/usr/local/lib/libh3.1.a` (static library - this is the default) or at `/usr/local/lib/libh3.1.dylib` (dynamic library)?

If it's the first (`.a`), please try rebuilding and reinstalling H3 as a shared library:
```
cmake -DBUILD_SHARED_LIBS=ON .
make
sudo make install
```

You might need to rebuild your extension before retrying.

If that doesn't help, do you know if there's a way to set your extension to statically link to H3? This is what we do in the Java bindings and it avoids this issue.

**Comment by neatlife** [comment]
otool output:

![image](https://user-images.githubusercontent.com/4076198/42983995-a14cf5ac-8c1c-11e8-9b95-20cfd0b0a19c.png)

I run the below command, and recompile extension, but error still exists

```
cmake -DBUILD_SHARED_LIBS=ON .
make
sudo make install
```
![image](https://user-images.githubusercontent.com/4076198/42984039-0172d370-8c1d-11e8-94ea-b57288a936cb.png)

![image](https://user-images.githubusercontent.com/4076198/42984066-2f871dde-8c1d-11e8-9eba-38ffee20054b.png)


I search some article, but not find a way to link to h3 library in php extension.

**Comment by neatlife** [comment]
@isaacbrodsky @dfellis I already fix this error, just pull the latest h3 code, and add link to h3 library https://github.com/neatlife/php-h3/commit/6cedacddb5573ba089f83012a9d500527e0c87ab, thank you.
