### ISSUE TITLE
area/edge length functions appear to be incorrect

### ISSUE THREAD

**Issue by afl5c** [uber/h3#98]
The area/edge length functions don't appear to be correct when compared with results from k-ring functions. Here is a sample program demonstrating the inconsistency:

```cpp
int main(){
    GeoCoord sf; //san francisco
    sf.lat = 37.783333;
    sf.lon = -122.416667;

    GeoCoord mv; //mountain view
    mv.lat = 37.389444l;
    mv.lon = -122.081944;
    
    printf("distance = %g km\n",haversineDistance(degsToRads(sf.lat),degsToRads(sf.lon),degsToRads(mv.lat),degsToRads(mv.lon)));
    
    int res = 3;
    printf ("res = %d\n",res);
    printf("area at res = %g km^2\n",hexAreaKm2(res));
    printf("edge length at res = %g km\n",edgeLengthKm(res));
    
    H3Index h = geoToH3(&sf,res);
    H3Index t = geoToH3(&mv,res);
    
    //keep expanding k until we find t
    int k;
    for(k=0;k<100;k++){
        int max = maxKringSize(k);
        H3Index* out = (H3Index*) calloc(max,sizeof(H3Index));
        kRing(h,k,out);
        int n;
        for(n=0;n<max;n++){
            if(out[n]==t){
                printf("Found! k = %d\n",k);
                return 0;
            }
        }
        free(out);
    }
}
```

The output is:
```
distance = 52.8034 km
res = 3
area at res = 12392.3 km^2
edge length at res = 59.8109 km
Found! k = 32
```

This appears incorrect because at resolution = 3, if each hexagon has an edge length of ~60 km, it shouldn't take k = 32 to find a hexagon only ~53 km away.

Also, it is unclear how the area is calculated. A hexagon with side length 60 km should have an area of ~9353 km^2, according to Google. So where is the 12,392 km^2 coming from?

So it appears that the area/edge functions are incorrect.

**Comment by nrabinowitz** [comment]
The edge length and area functions just return constant values: https://github.com/uber/h3/blob/master/src/h3lib/lib/geoCoord.c#L257

@isaacbrodsky, do you have more info on how these constants were calculated? They are definitely not exact, and there will be differences across cells due to distortion, but this difference should be within a small margin of error.

Regardless, something is incorrect here - res 3 is quite coarse, and the MV cell should be a direct neighbor of the SF cell:

<img width="708" alt="screen shot 2018-07-23 at 8 42 32 am" src="https://user-images.githubusercontent.com/163940/43087357-8a8bfd2e-8e54-11e8-832a-ad305dc83bb5.png">

**Comment by nrabinowitz** [comment]
Ok, took me a second. You are directly setting the lat/lon on your `GeoCoord` structs but the struct actually expects radians, not degrees. To set degrees, use `setGeoDegs(GeoCoord* p, double latDegs, double lonDegs)`.

Update to:
```
GeoCoord sf; //san francisco
    setGeoDegs(&sf, 37.783333, -122.416667);

    GeoCoord mv; //mountain view
    setGeoDegs(&mv, 37.389444,  -122.081944);
```
and you get:
```
Found! k = 1
```
as expected.
